2021-07-31 11:44:25,939 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
2021-07-31 11:44:28,229 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
2021-07-31 11:44:33,292 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
2021-07-31 11:44:35,841 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
2021-07-31 11:44:40,883 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
2021-07-31 11:44:43,448 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
2021-07-31 11:44:50,559 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
