2021-08-10 14:38:51,403 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-10 14:41:57,497 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-10 14:41:59,272 ERROR: Exception on /api/countries [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\api\countries.py", line 9, in get_countries
    users = Countries.query.all()
NameError: name 'Countries' is not defined
2021-08-10 14:43:02,012 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-10 14:43:03,727 ERROR: Exception on /api/countries [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\api\countries.py", line 9, in get_countries
    users = Users.query.all()
NameError: name 'Users' is not defined
2021-08-10 14:43:35,494 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-10 14:43:37,709 ERROR: Exception on /api/countries [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\api\countries.py", line 9, in get_countries
    users = User.query.all()
NameError: name 'User' is not defined
2021-08-10 14:44:32,125 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-10 14:44:35,776 ERROR: Exception on /api/countries [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1728, in make_response
    "The view function did not return a valid"
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
2021-08-10 14:45:38,424 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-10 14:45:40,344 ERROR: Exception on /api/countries [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\api\countries.py", line 12, in get_countries
    return jsonify(users)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 348, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 129, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 56, in default
    return super().default(o)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
2021-08-10 14:47:17,891 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-10 14:47:22,533 ERROR: Exception on /api/countries [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\api\countries.py", line 12, in get_countries
    return jsonify(users)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 348, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 129, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 56, in default
    return super().default(o)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
2021-08-10 14:48:08,561 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
