2021-07-31 11:47:14,427 ERROR: Exception on /api/users [POST] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 164, in create_user
    response = jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
2021-07-31 11:47:51,413 ERROR: Exception on /api/users [POST] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 164, in create_user
    response = jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
