2021-07-31 11:16:04,501 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-07-31 11:18:06,676 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-07-31 11:19:02,294 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-07-31 11:26:36,111 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-07-31 11:40:08,078 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-07-31 11:41:40,797 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-07-31 11:43:37,032 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
2021-07-31 11:43:41,840 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
2021-07-31 11:43:58,032 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
2021-07-31 11:44:00,582 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
2021-07-31 11:44:05,621 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
2021-07-31 11:44:08,166 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
2021-07-31 11:44:15,740 ERROR: Exception on /api/users/aliahmed [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "C:\xampp\htdocs\onely\app\api\users.py", line 190, in get_user_by_username
    return jsonify(user.to_dict())
  File "C:\xampp\htdocs\onely\app\models.py", line 139, in to_dict
    'last_seen': int(float(self.last_seen.strftime('%s.%f'))*1000),
ValueError: Invalid format string
